name: PWA103 - manual workflow

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Chọn môi trường'
        required: true
        type: choice
        options:
          - dev
          - staging
          - production
        default: 'dev'
      test_tags:
        description: "Nhập vào tag để chạy (Format: @t1 hoặc @t1|@t2)"
        required: true
        type: string

jobs:
  execute-tests:
    name: Run ${{ inputs.test_tag }} tests on ${{ inputs.env }}
    runs-on: ubuntu-latest

    steps:
      - name: Pull code repo ve
        uses: actions/checkout@v4
      - name: In ra các lựa chọn đã chọn
        run: |
          echo "Target Env: ${{ inputs.env }}"
          echo "Test tag: ${{ inputs.test_tags }}"
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
      - name: Cài đặt thư viện
        run: npm i
      - name: Cài đặt trình duyệt Playwright
        run: npx playwright install --with-deps
      - name: Chạy test
        run: ENV=${{ inputs.env }} npx playwright test -g "${{ inputs.test_tags }}"
      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 14